apiVersion: v1
kind: cypress
showConsoleLog: false
rootDir: ./
sauce:
  region: us-west-1
cypress:
  configFile: cypress.config.js
  version: 13.3.0
  record: false
  key: ""
proxy-tunnel: true
suites:
  - name: "Chrome on Windows 11"
    browser: "chrome"
    platformName: "Windows 11"
    config:
      specPattern:  [ "./cypress/e2e/*.cy.*"  ]